# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
en:
  locale: en-us
  label: English
  weight: 1

ja:
  locale: ja
  label: 日本語
  weight: 2
  menus:
    main:
      - name: Home
        url: https://jkoba0512.github.io/jkoba-lab/
        weight: 10
      - name: Research
        url: https://jkoba0512.github.io/jkoba-lab/#section-focus-areas
        weight: 30
      - name: People
        url: https://jkoba0512.github.io/jkoba-lab/people/
        weight: 40
      - name: Publications
        url: https://jkoba0512.github.io/jkoba-lab/publications/
        weight: 50
      - name: News
        url: https://jkoba0512.github.io/jkoba-lab/#news
        weight: 20
      - name: About
        url: https://jkoba0512.github.io/jkoba-lab/about/
        weight: 60
